[package]
name = "sitrephq"
version = "0.1.0"
edition = "2024"
description = "A self-hosted status dashboard with flexibility"
license = "MIT"
repository = "https://github.com/lamplitkeep/sitrephq"
readme = "../README.md"
keywords = ["dashboard", "homelab", "monitoring", "selfhosted"]
categories = ["command-line-utilities"]

[[bin]]
name = "sitrep"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
async-stream = "0.3.6"
async-trait = "0.1.92"
axum = { version = "0.8.9", features = ["json"] }
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
base64 = "0.23.1"
dotenvy = "0.15.7"
futures = "0.3.34"
humantime-serde = "1.1.1"
mime_guess = "2.0.5"
reqwest = { version = "0.13.4", features = ["json"] }
rust-embed = { version = "8.12.0", features = ["axum"] }
serde = { version = "1.0.229", features = ["derive"] }
serde-saphyr = { version = "1.1.0", features = ["include"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tokio-stream = "0.1.19"
tower-http = { version = "0.7.0", features = ["fs", "set-header"] }
